CREATE TABLE IF NOT EXISTS "users" (
    "id" VARCHAR(36) PRIMARY KEY NOT NULL,
    "profilePhotoId" VARCHAR(36) NULL,
    "email" VARCHAR(255) UNIQUE NOT NULL,
    "fullName" VARCHAR(255) NULL,
    "password" VARCHAR(255) NOT NULL,
    "department" VARCHAR(255) NULL,
    "securityScore" INTEGER NOT NULL DEFAULT 0,
    "accessToken" TEXT NULL,
    "refreshToken" TEXT NULL,
    "verificationToken" TEXT NULL,
    "forgotPasswordToken" TEXT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT TRUE,
    "isEmailVerified" BOOLEAN NOT NULL DEFAULT FALSE,
    "lastLoginAt" BIGINT NULL,
    "forgotPasswordAt" BIGINT NULL,
    "createdAt" BIGINT NOT NULL DEFAULT 0,
    "createdBy" VARCHAR(36) NULL,
    "updatedAt" BIGINT NOT NULL DEFAULT 0,
    "updatedBy" VARCHAR(36) NULL,
    "isDeleted" BOOLEAN NOT NULL DEFAULT FALSE,

    CREATE INDEX IF NOT EXISTS "idx_users_email" ON "users" ("email"),
    CREATE INDEX IF NOT EXISTS "idx_users_id" ON "users" ("id"),
);